---
# necessary steps to configure the role

- name: install base condarc
  copy: src={{ item }} dest="~/.{{ item }}" force=no
  with_items:
    - condarc
  when: miniconda_add_condarc

- name: add miniconda to the PATH
  lineinfile:
    dest: "{{ miniconda_rcfile }}"
    line: export PATH={{ miniconda_home }}/bin:$PATH
    state: present
  when: miniconda_modify_path

- name: create environments
  shell: "{{ miniconda_home }}/bin/conda create --yes -q -n {{ item.name }} python={{ item.python_version }} {{ item.pkgs }} creates={{ miniconda_home }}/envs/{{ item.name }}"
  with_items:
     - "{{ miniconda_environments }}"
  when: miniconda_installed is success
